uciData = read.table("./household_power_consumption.txt", header = TRUE, sep=";")
library(lubridate)
uciData$Date = dmy(uciData$Date)
d1 = ymd("2007-02-01")
d2 = ymd("2007-02-02")
newData = uciData[uciData$Date == d1 | uciData$Date == d2,]
newData$Time = hms(newData$Time)
newData$Sub_metering_1 = as.character(newData$Sub_metering_1)
newData$Sub_metering_2 = as.character(newData$Sub_metering_2)
newData$Sub_metering_3 = as.character(newData$Sub_metering_3)
newData$Sub_metering_1 = as.numeric(newData$Sub_metering_1)
newData$Sub_metering_2 = as.numeric(newData$Sub_metering_2)
newData$Sub_metering_3 = as.numeric(newData$Sub_metering_3)
png(filename = "plot3.png", height = 480, width = 480)
plot(1:2880, newData$Sub_metering_1, type="l", xaxt="n", xlab = "", ylab = "Energy sub metering", col = "black")
lines(1:2880, newData$Sub_metering_2, type="l", xaxt="n", xlab = "", ylab = "Energy sub metering", col = "red")
lines(1:2880, newData$Sub_metering_3, type="l", xaxt="n", xlab = "", col = "blue",
     ylab = "Energy sub metering")
newXaxis = seq(from = 0, to = 2880, by = 1440)
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty = c(1,1,1), col = c("black","red","blue"))
axis(side = 1, at = newXaxis, labels=c("Thu", "Fri", "Sat"))
axis(side = 2, at = newYaxis)
dev.off()